# Generated by Django 4.0.6 on 2022-07-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='companylogo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unique_about_solution',
        ),
        migrations.RemoveField(
            model_name='application',
            name='value_proportion_for_customer',
        ),
    ]
