# Generated by Django 4.0.6 on 2022-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_slot_remove_application_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.AddField(
            model_name='application',
            name='slot',
            field=models.BooleanField(default=False),
        ),
    ]
