# Generated by Django 4.0.6 on 2022-07-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_slot_application_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='slot',
            new_name='slotactive',
        ),
        migrations.CreateModel(
            name='Slotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('slotnumber', models.CharField(max_length=10)),
                ('Active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
        ),
    ]
