# Generated by Django 4.0.6 on 2022-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_application_incubation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='companylogo',
            field=models.ImageField(default=None, max_length=20, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='incubation_type',
            field=models.CharField(choices=[('Physicalincubation', 'Physicalincubation'), ('Virtualincubation', 'Virtualincubation')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
