# Generated by Django 4.0.6 on 2022-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_application_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='companylogo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
