# Generated by Django 4.0.6 on 2022-07-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_slotbooking_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='session',
        ),
    ]
