# Generated by Django 4.0.6 on 2022-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_slotbooking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='session',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
