# Generated by Django 4.0.6 on 2022-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_slotbooking_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='session',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100),
        ),
    ]
