# Generated by Django 4.0.6 on 2022-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_slotbooking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='advantage_competative',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='describe_problem',
            field=models.TextField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='describtion_on_products',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='how_market',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='market_product_size',
            field=models.TextField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='revenue_model',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='unique_about_solution',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='value_proportion_for_customer',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='companylogo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='session',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=100),
        ),
    ]
