# Generated by Django 4.0.6 on 2022-07-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_application_advantage_competative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='companylogo',
        ),
    ]
