# Generated by Django 4.0.6 on 2022-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_application_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='companylogo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
