# Generated by Django 4.0.6 on 2022-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_application_companylogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='companylogo',
        ),
        migrations.AlterField(
            model_name='application',
            name='advantage_competative',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='describe_problem',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='describtion_on_company',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='describtion_on_products',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='describtion_on_team',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='how_market',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='incubation_type',
            field=models.CharField(blank=True, choices=[('Physicalincubation', 'Physicalincubation'), ('Virtualincubation', 'Virtualincubation')], max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='market_product_size',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='revenue_model',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='unique_about_solution',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='value_proportion_for_customer',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
